# Last generated by genNikonCameras.py on 2025-11-01 11:43:20.005343

#
# cameras.py - Generated file with database of EXIF info from various cameras
#

# imports
from   typing import Any, Callable, List, NamedTuple, Tuple, Type
from   enum import Enum

# types
Dimensions = NamedTuple('Dimensions', [('columns', int), ('rows', int)])
EmbeddedJpg = NamedTuple('EmbeddedJpg', [('exifName', str), ('dimensions', Dimensions)])
CameraInfo = NamedTuple('CameraInfo', [('model', str), ('rawDimensions', Dimensions), ('blackLevel', int), ('embeddedJpgs', list)])

# methods
def getCamera(model: str) -> CameraInfo:
    if model in CameraInfos:
        return CameraInfos[model]
    return None
    
def listCameras() -> None:
    for index, (model, cameraInfo) in enumerate(CameraInfos.items()):
        modelStrPadded = f'"{model}"'.ljust(10)
        firstJpg = cameraInfo.embeddedJpgs[0]
        firstJpgInfoStr = f"JPG: {firstJpg.dimensions.columns}x{firstJpg.dimensions.rows}" if firstJpg else ""
        print(f"{modelStrPadded} RAW: {cameraInfo.rawDimensions.columns}x{cameraInfo.rawDimensions.rows}, {firstJpgInfoStr}")
        

CameraInfos = dict()
CameraInfos["D3"] = CameraInfo(model="D3", rawDimensions=Dimensions(columns=4288, rows=2844), blackLevel=0,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=4256, rows=2832)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=570, rows=375)),
])
CameraInfos["D300"] = CameraInfo(model="D300", rawDimensions=Dimensions(columns=4352, rows=2868), blackLevel=0,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=4288, rows=2848)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=570, rows=375)),
])
CameraInfos["D300S"] = CameraInfo(model="D300S", rawDimensions=Dimensions(columns=4352, rows=2868), blackLevel=0,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=4288, rows=2848)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=570, rows=375)),
])
CameraInfos["D3S"] = CameraInfo(model="D3S", rawDimensions=Dimensions(columns=4288, rows=2844), blackLevel=0,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=4256, rows=2832)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=570, rows=375)),
])
CameraInfos["D3X"] = CameraInfo(model="D3X", rawDimensions=Dimensions(columns=6080, rows=4044), blackLevel=0,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=6048, rows=4032)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=570, rows=375)),
])
CameraInfos["D4"] = CameraInfo(model="D4", rawDimensions=Dimensions(columns=4992, rows=3292), blackLevel=0,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=4928, rows=3280)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1632, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=570, rows=375)),
])
CameraInfos["D4S"] = CameraInfo(model="D4S", rawDimensions=Dimensions(columns=4936, rows=3288), blackLevel=768,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=4928, rows=3280)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=640, rows=424)),
])
CameraInfos["D5"] = CameraInfo(model="D5", rawDimensions=Dimensions(columns=5584, rows=3728), blackLevel=400,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=5568, rows=3712)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=640, rows=424)),
])
CameraInfos["D500"] = CameraInfo(model="D500", rawDimensions=Dimensions(columns=5600, rows=3728), blackLevel=400,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=5568, rows=3712)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=640, rows=424)),
])
CameraInfos["D5100"] = CameraInfo(model="D5100", rawDimensions=Dimensions(columns=4992, rows=3280), blackLevel=0,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=4928, rows=3264)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=570, rows=375)),
])
CameraInfos["D5200"] = CameraInfo(model="D5200", rawDimensions=Dimensions(columns=6036, rows=4020), blackLevel=0,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=6000, rows=4000)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=570, rows=375)),
])
CameraInfos["D5300"] = CameraInfo(model="D5300", rawDimensions=Dimensions(columns=6016, rows=4016), blackLevel=600,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=6000, rows=4000)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=640, rows=424)),
])
CameraInfos["D5500"] = CameraInfo(model="D5500", rawDimensions=Dimensions(columns=6016, rows=4016), blackLevel=600,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=6000, rows=4000)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=640, rows=424)),
])
CameraInfos["D5600"] = CameraInfo(model="D5600", rawDimensions=Dimensions(columns=6016, rows=4016), blackLevel=600,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=6000, rows=4000)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=640, rows=424)),
])
CameraInfos["D6"] = CameraInfo(model="D6", rawDimensions=Dimensions(columns=5584, rows=3728), blackLevel=1008,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=5568, rows=3712)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=640, rows=424)),
])
CameraInfos["D600"] = CameraInfo(model="D600", rawDimensions=Dimensions(columns=6080, rows=4028), blackLevel=0,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=6016, rows=4016)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1632, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=570, rows=375)),
])
CameraInfos["D610"] = CameraInfo(model="D610", rawDimensions=Dimensions(columns=6080, rows=4028), blackLevel=0,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=6016, rows=4016)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1632, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=570, rows=375)),
])
CameraInfos["D700"] = CameraInfo(model="D700", rawDimensions=Dimensions(columns=4288, rows=2844), blackLevel=0,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=4256, rows=2832)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=570, rows=375)),
])
CameraInfos["D7000"] = CameraInfo(model="D7000", rawDimensions=Dimensions(columns=4992, rows=3280), blackLevel=0,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=4928, rows=3264)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=570, rows=375)),
])
CameraInfos["D7100"] = CameraInfo(model="D7100", rawDimensions=Dimensions(columns=6036, rows=4020), blackLevel=0,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=6000, rows=4000)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=570, rows=375)),
])
CameraInfos["D7200"] = CameraInfo(model="D7200", rawDimensions=Dimensions(columns=6016, rows=4016), blackLevel=600,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=6000, rows=4000)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=640, rows=424)),
])
CameraInfos["D750"] = CameraInfo(model="D750", rawDimensions=Dimensions(columns=6032, rows=4032), blackLevel=600,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=6016, rows=4016)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=640, rows=424)),
])
CameraInfos["D7500"] = CameraInfo(model="D7500", rawDimensions=Dimensions(columns=5600, rows=3728), blackLevel=400,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=5568, rows=3712)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=640, rows=424)),
])
CameraInfos["D780"] = CameraInfo(model="D780", rawDimensions=Dimensions(columns=6064, rows=4040), blackLevel=1008,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=6048, rows=4024)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=640, rows=424)),
])
CameraInfos["D800"] = CameraInfo(model="D800", rawDimensions=Dimensions(columns=7424, rows=4924), blackLevel=0,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=7360, rows=4912)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1632, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=570, rows=375)),
])
CameraInfos["D800E"] = CameraInfo(model="D800E", rawDimensions=Dimensions(columns=7424, rows=4924), blackLevel=0,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=7360, rows=4912)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1632, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=570, rows=375)),
])
CameraInfos["D810"] = CameraInfo(model="D810", rawDimensions=Dimensions(columns=7380, rows=4928), blackLevel=600,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=7360, rows=4912)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=640, rows=424)),
])
CameraInfos["D810A"] = CameraInfo(model="D810A", rawDimensions=Dimensions(columns=7380, rows=4928), blackLevel=600,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=7360, rows=4912)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=640, rows=424)),
])
CameraInfos["D850"] = CameraInfo(model="D850", rawDimensions=Dimensions(columns=8288, rows=5520), blackLevel=400,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=8256, rows=5504)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=640, rows=424)),
])
CameraInfos["DF"] = CameraInfo(model="DF", rawDimensions=Dimensions(columns=4992, rows=3292), blackLevel=0,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=4928, rows=3280)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=570, rows=375)),
])
CameraInfos["Z30"] = CameraInfo(model="Z30", rawDimensions=Dimensions(columns=5600, rows=3728), blackLevel=1008,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=5568, rows=3712)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=640, rows=424)),
])
CameraInfos["Z5"] = CameraInfo(model="Z5", rawDimensions=Dimensions(columns=6040, rows=4032), blackLevel=1008,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=6016, rows=4016)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=640, rows=424)),
])
CameraInfos["Z50"] = CameraInfo(model="Z50", rawDimensions=Dimensions(columns=5600, rows=3728), blackLevel=1008,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=5568, rows=3712)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=640, rows=424)),
])
CameraInfos["Z5II"] = CameraInfo(model="Z5II", rawDimensions=Dimensions(columns=6064, rows=4040), blackLevel=1008,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=6048, rows=4032)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=640, rows=424)),
        EmbeddedJpg(exifName="Thumbnail", dimensions=Dimensions(columns=160, rows=120)),
])
CameraInfos["Z6II"] = CameraInfo(model="Z6II", rawDimensions=Dimensions(columns=6064, rows=4040), blackLevel=1008,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=6048, rows=4024)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=640, rows=424)),
])
CameraInfos["Z6III"] = CameraInfo(model="Z6III", rawDimensions=Dimensions(columns=6064, rows=4040), blackLevel=1008,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=6048, rows=4032)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=640, rows=424)),
        EmbeddedJpg(exifName="Thumbnail", dimensions=Dimensions(columns=160, rows=120)),
])
CameraInfos["Z7II"] = CameraInfo(model="Z7II", rawDimensions=Dimensions(columns=8288, rows=5520), blackLevel=1008,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=8256, rows=5504)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=640, rows=424)),
])
CameraInfos["Z8"] = CameraInfo(model="Z8", rawDimensions=Dimensions(columns=8280, rows=5520), blackLevel=1008,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=8256, rows=5504)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=640, rows=424)),
        EmbeddedJpg(exifName="Thumbnail", dimensions=Dimensions(columns=160, rows=120)),
])
CameraInfos["Z9"] = CameraInfo(model="Z9", rawDimensions=Dimensions(columns=8280, rows=5520), blackLevel=1008,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=8256, rows=5504)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=640, rows=424)),
        EmbeddedJpg(exifName="Thumbnail", dimensions=Dimensions(columns=160, rows=120)),
])
CameraInfos["ZF"] = CameraInfo(model="ZF", rawDimensions=Dimensions(columns=6064, rows=4040), blackLevel=1008,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=6048, rows=4032)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=640, rows=424)),
        EmbeddedJpg(exifName="Thumbnail", dimensions=Dimensions(columns=160, rows=120)),
])
CameraInfos["ZFC"] = CameraInfo(model="ZFC", rawDimensions=Dimensions(columns=5600, rows=3728), blackLevel=1008,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=5568, rows=3712)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=640, rows=424)),
])
CameraInfos["Z50II"] = CameraInfo(model="Z50II", rawDimensions=Dimensions(columns=5600, rows=3728), blackLevel=1008,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=5568, rows=3712)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=640, rows=424)),
        EmbeddedJpg(exifName="Thumbnail", dimensions=Dimensions(columns=160, rows=120)),
])
CameraInfos["Z6"] = CameraInfo(model="Z6", rawDimensions=Dimensions(columns=6064, rows=4040), blackLevel=1008,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=6048, rows=4024)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=640, rows=424)),
])
CameraInfos["Z7"] = CameraInfo(model="Z7", rawDimensions=Dimensions(columns=8288, rows=5520), blackLevel=1008,embeddedJpgs=[
        EmbeddedJpg(exifName="JpgFromRaw", dimensions=Dimensions(columns=8256, rows=5504)),
        EmbeddedJpg(exifName="OtherImage", dimensions=Dimensions(columns=1620, rows=1080)),
        EmbeddedJpg(exifName="PreviewImage", dimensions=Dimensions(columns=640, rows=424)),
])

if __name__ == "__main__":
    listCameras()

